[package]
name = "goaties-common"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
chrono = "0.4"
polodb_core = { version = "5.1", optional = true }

[features]
polodb = ["polodb_core"]
